### PR TITLE
[WIP] Crosscompile with MinGW, run with WINE

### PR DESCRIPTION
**Pull request by franciscod**
mingw-wine-gaben

> mfw Terminal Terminal Terminal

this is a somewhat dirty branch on which i'm testing cross compiling on linux to mingw-w64 :dancer:

based on mappu's work on #9 and former work at #207. also [this unnamed branch similar to mappu's guide](https://github.com/franciscod/openage/tree/a4519112381fe7dd8ceed3377d620dc548064d07) 

---
## Prerequisites
- You can build and run openage on your native platform without issues
- You have Wine and mingw-w64 installed plus all the dependencies in their mingw crosscompiled form [example: AUR](https://aur.archlinux.org/packages/?K=mingw-w64))
## The four super hard steps to see gaben under wine

```
$ ./buildsystem/mingw-configure    # generates config.h, we're not using cmake yet
$ ./buildsystem/mingw-build-simple # compiles
$ ./buildsystem/mingw-deploy       # copies .exe and dlls
$ ./buildsystem/mingw-run-wine     # calls wine with fontconfig settings
```

---
## Issues (need help!)
- [x] compile with a simple build script based on `buildsystem/simple` (`buildsystem/mingw-build-simple`)
- [x] fix the fontconfig slow loading at startup
- [ ] improve the random fontconfig solution (see the `buildsystem/mingw-run-wine` envvar)
- [ ] integrate cleanly with cmake instead of breaking `configure`
- [ ] find a way to package it for bare windows7 (xp? vista?) 32bit (with dlls and every dep needed)
- [ ] fix skewed gaben texture

### CODE REVIEW

**Comment by franciscod** [comment]
please test and comment!

**Comment by franciscod** [comment]
GUYS GUYS IT RAN ON WINE, BUT CLOSED WITH THIS ERROR:

```
MSG   ERROR: tokenizing graphic led to 18 columns (expecting 16)!
FATAL Exception: tokenizing graphic led to 18 columns (expecting 16)!
```

wtf is this i don't even (inb4 make media)

**Comment by franciscod** [comment]
HOLY SHIT GABEN ON WINE CROSSCOMPILEDDDDDDDD 


IT WORKS FINE, SOUND AND EVERYTHING AND HNNNNGGGGGGG

**Comment by franciscod** [comment]
### it runs on windows!

uxp openage

removing the `-mwindows` flag from the simple build script enabled the output ond stdout, and then the fontconfig error was evident. A `.bat` fixed it like as the `mingw-run-wine`: setting the `FONTCONFIG_PATH` envvar to `dist-win32` did the trick!

Now... what's the best solution for that fontconfig issue? I don't like setting that envvar, seems like a workaround

**Comment by TheJJ** [comment]
would also be nice if you can update it to the new project layout.

**Comment by franciscod** [comment]
I'll take a look :)

**Comment by franciscod** [comment]
Slightly related question: should we support Windows XP? What about Windows 98? :older_man:

**Comment by TheJJ** [comment]
dunno, i think targetting winxp is ok, soon we'll require opengl 3.2 or even 3.3, dunno if that works under xp.

**Comment by franciscod** [comment]
i'm starting the update of this one right now

**Comment by franciscod** [comment]
okay: rebased... but... wtf PYTHONTEX?!?!

```
% ./buildsystem/mingw-configure                                                                                                                     ~/src/openage 1 22:31
./configure is a convenience script that creates the build directory,
symlinks it, and invokes cmake for an out-of-source build.

Nobody is stopping you from skipping ./configure and Makefile,
and using CMake directly (e.g. when packaging, or using an IDE).
For your convenience, ./configure even prints the direct CMake invocation!

compiler suite: gnu

         build_type | Debug
         c_compiler | gcc
            c_flags | 
       cxx_compiler | g++
          cxx_flags | 
   exe_linker_flags | 
     install_prefix | /usr/local
module_linker_flags | 
shared_linker_flags | 

config options:

          backtrace | if_available
gperftools-profiler | if_available
gperftools-tcmalloc | False
            inotify | if_available

bindir:
/home/fd/src/openage/.bin/gcc-debug-Oauto-sanitize-none/

invocation:
i686-w64-mingw32-cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_COMPILER=gcc -DCMAKE_C_FLAGS='' -DCMAKE_CXX_COMPILER=g++ -DCMAKE_CXX_FLAGS='' -DCMAKE_EXE_LINKER_FLAGS='' -DCMAKE_INSTALL_PREFIX=/usr/local -DCMAKE_MODULE_LINKER_FLAGS='' -DCMAKE_SHARED_LINKER_FLAGS='' -DCXX_OPTIMIZATION_LEVEL=auto -DCXX_SANITIZE_FATAL=False -DCXX_SANITIZE_MODE=none -DWANT_BACKTRACE=if_available -DWANT_GPERFTOOLS_PROFILER=if_available -DWANT_GPERFTOOLS_TCMALLOC=False -DWANT_INOTIFY=if_available -- /home/fd/src/openage

(running cmake...)

 ___  ______ _______ _______ ___
|  _)/ _____|_______|_______|_  |
| | ( (____  _____      _     | |    ___  ____  _____ ____  _____  ____ _____
| |  \____ \|  ___)    | |    | |   / _ \|  _ \| ___ |  _ \(____ |/ _  | ___ |
| |_ _____) ) |        | |   _| |  | |_| | |_| | ____| | | / ___ ( (_| | ____|
|___|______/|_|        |_|  (___|   \___/|  __/|_____)_| |_\_____|\___ |_____)
                                         |_|                     (_____|

Welcome to the SFT technologies computer-aided openage build system!

You have chosen, or been chosen, to attempt the daring task of building openage.
If you have installed all the dependencies that are conveniently listed in
[doc/building.md], this _might_ just work!

If it doesn't, consider reporting the issue/asking for help in #sfttech on freenode.net.

-- The C compiler identification is GNU 5.3.0
-- The CXX compiler identification is GNU 5.3.0
-- Check for working C compiler: /usr/bin/i686-w64-mingw32-gcc
-- Check for working C compiler: /usr/bin/i686-w64-mingw32-gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/i686-w64-mingw32-g++
-- Check for working CXX compiler: /usr/bin/i686-w64-mingw32-g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test GCC_SUPPORTS_CPP14
-- Performing Test GCC_SUPPORTS_CPP14 - Success
-- Performing Test HAVE_THREAD_LOCAL_STORAGE
-- Performing Test HAVE_THREAD_LOCAL_STORAGE - Success
CMake Error at buildsystem/modules/FindPython.cmake:29 (message):
  failed:

  /usr/share/texmf-dist/scripts/pythontex/pythontex.py -c 'from
  distutils.sysconfig import get_config_var;
  print(get_config_var("INCLUDEPY"))'

  usage: pythontex.py [-h] [--version] [--encoding ENCODING]

                      [--error-exit-code {true,false}] [--runall [{true,false}]
                      | --rerun {never,modified,errors,warnings,always}]
                      [--hashdependencies [{true,false}]] [-j N] [-v]
                      [--interpreter INTERPRETER]
                      [--debug [<family>:<session>:<restart>] | --interactive
                      [<family>:<session>:<restart>]]
                      TEXNAME

  pythontex.py: error: unrecognized arguments: -c
Call Stack (most recent call first):
  buildsystem/modules/FindPython.cmake:37 (py_exec)
  buildsystem/modules/FindPython.cmake:128 (py_get_config_var)
  buildsystem/HandlePythonOptions.cmake:6 (find_package)
  CMakeLists.txt:57 (include)


-- Configuring incomplete, errors occurred!
See also "/home/fd/src/openage/.bin/gcc-debug-Oauto-sanitize-none/CMakeFiles/CMakeOutput.log".
```

**Comment by franciscod** [comment]
This one is brewing:
- I tried Ubuntu (and failed)
- then Arch (and failed too because of [this mingw-w64-python is 3.4 instead of 3.5](https://aur.archlinux.org/packages/mingw-w64-python) 
- and @TheJJ was trying to cross-compile on Gentoo

**Comment by TheJJ** [comment]
This is kind of obsolete, am I right?

**Comment by franciscod** [comment]
yuuuuuuuup

**Pull request closed without merging**
