### PR TITLE
crossplattform: enable math constants on all plattforms

### PR DESCRIPTION
**Pull request by TheJJ**
This introduces namespaced math constants available on all plattforms.

closes #208.

### CODE REVIEW

**Comment by franciscod** [comment]
awesome! :+1:

**Comment by franciscod** [comment]
see the previous comment. I think it breaks because cmath gets imported earlier in the build process without the `_USE_MATH_DEFINES` macro defined.

**Comment by franciscod** [comment]
however, on linux it builds fine, lol

**Comment by franciscod** [comment]
i'm poor man's travis

**Comment by TheJJ** [comment]
Hmm, but then i see no other solution than defining the constants manually to the actual numbers.

We can't manipulate the inclusion order and devs will want to include `<cmath>` without thinking about breaking the constant definitions..

**Comment by franciscod** [comment]
These guys were defining that macro on CMakeLists, but since then migrated too boost.

https://github.com/ddemidov/vexcl/commit/696d74a44d406e979ebbe37dc4a1bd924e0d8358
---

>The math library normally defines M_PI to a double approximation of pi. If strict ISO and/or POSIX >compliance are requested this constant is not defined, but you can easily define it yourself:
>
>`#define M_PI 3.14159265358979323846264338327`
>You can also compute the value of pi with the expression acos (-1.0).

http://www.sbin.org/doc/glibc/libc_19.html

---

My vote is also hardcode the constants without relying on the cmath behaviour.

**Comment by franciscod** [comment]
https://github.com/TheJJ/openage/pull/1

[!yo](http://imgur.com/JCoTMVx)

**Comment by franciscod** [comment]
typo on crossplat**t**form!

**Comment by TheJJ** [comment]
oh lol :facepunch:

i think it should be with one `t`, as far as http://www.dict.cc/?s=platform is telling me

**Comment by franciscod** [comment]
builds fine on msys2 now, :+1:

**Comment by franciscod** [comment]
half typos remaining!
```
crossplatform: namespaced math constants on all plattforms
        ^                                          ^
        |                                          |-NOT OK
        |-OK                                          
```

**Comment by fr3akout** [comment]
:+1:

**Pull request merged**
