### PR TITLE
Better graphics handling for unit data

### PR DESCRIPTION
**Pull request by Jon0**

### CODE REVIEW

**Comment by TheJJ** [comment]
Welcome back, jon :kissing_heart:

**Comment by TheJJ** [comment]
Please tell me when you want to have this merged :)

**Comment by Jon0** [comment]
I rebased and amended the commit times to hopefully fix the date issues.

**Comment by TheJJ** [comment]
Still some 2015s left :(
remember that you can run `make checkall` on your local machine that does the same checks as travis.

**Comment by ChipmunkV** [comment]
@TheJJ, `make checkall` doesn't exist as a target.

**Comment by TheJJ** [comment]
@ChipmunkV I don't know where you looked for make targets, but it's here:

https://github.com/SFTtech/openage/blob/5f911b239e17aa0461d8ef512caf55c6ef34cf7e/Makefile#L124

**Comment by ChipmunkV** [comment]
Thanks, I've looked in the build dir obviously.

**Comment by Jon0** [comment]
This refactor should be complete now. The big changes are moving unit types into a new civilisation class, and villagers unit type is modified when gathering resources, instead of just overriding the graphic.

**Comment by TheJJ** [comment]
code :white_check_mark: 
quick gameplay test :white_check_mark: 
awesome :white_check_mark:

**Pull request merged**
