### PR TITLE
buildsystem: fix opusfile, make it crossplatform

### PR DESCRIPTION
**Pull request by franciscod**
Look at this, it's beautiful! Copied the hard work of Unvanquished:
https://github.com/Unvanquished/Unvanquished/blob/master/cmake/FindOpus.cmake

works perfectly on GNU/Linux and MSYS2!!!

### CODE REVIEW

**Comment by franciscod** [comment]
hmmm licensing issues... how should we proceed?

**Comment by franciscod** [comment]
is this copying.md diff ok?

**Comment by TheJJ** [comment]
i'm just looking into this, and reformatting the patch etc. `FindOpus.cmake` is licensed 3clause-bsd as the file states internally, it's not gplv3 because of unvanquished.

You can then push my branch to this pullrequest once i'm done :stuck_out_tongue_winking_eye:

**Comment by franciscod** [comment]
okay, thanks! :D

**Comment by TheJJ** [comment]
Kay, should be good now, see https://github.com/TheJJ/openage/tree/opus-cmake

If you like, you can push this branch to this pullrequest, alternatively i'll do a separate pull.

**Comment by franciscod** [comment]
Awesome! Do a separate pull and close both on merge :D

**Comment by TheJJ** [comment]
wheeee

**Pull request closed without merging**
