### PR TITLE
improved shader for team colored textures

### PR DESCRIPTION
**Pull request by ptolstoi**
resubmission: #202

### CODE REVIEW

**Comment by TheJJ** [comment]
I think this is ready for merge, but we have to keep #204 in mind. Otherwise many users will totally get confused why the game looks wrong for them after this is merged.

**Comment by franciscod** [comment]
This seems to break the colors a bit, have a look:

openage_2015-02-13_03-25-42_00

openage_2015-02-13_03-29-43_00

Can anyone repro?

**Comment by TheJJ** [comment]
that's why we need #204 to trigger a media reconversion :wink:

**Comment by franciscod** [comment]
after `make media`:
openage_2015-02-13_14-06-46_00

seems nice! I like the alpha on the "ghost" player when building is not yet placed. :+1: :ship: :it:

**Comment by mic-e** [comment]
What's the status of this?

@TheJJ: Is this still valid with #287 in progress?

**Comment by TheJJ** [comment]
it'll be integrated in #287 but also requires #265 / #204 to be completed.

**Pull request closed without merging**
