### PR TITLE
C++14 as new standard

### LINKED ISSUE #193: Switch minimum compiler version to GCC 4.9/Clang 3.5
There has been discussion on the IRC channel about ditching GCC 4.8/Clang 3.4 support in order to make use of some new language features.

The obvious downside is that parts of the user/developer base would need to upgrade their toolchains, which may or may not require unreasonable effort.

I have been assured that Clang 3.5 is available on OSX Mountain Lion and upwards through XCode 6. The recent compiler versions are available on Debian testing-soon-to-be-stable as well as the most recent (non-LTS) version of Ubuntu.

What about mingw cross-compilers and other Linux distributions?

This issue is intended as a platform for discussion.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/7910601-switch-minimum-compiler-version-to-gcc-4-9-clang-3-5?utm_campaign=plugin&utm_content=tracker%2F371436&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F371436&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by TheJJ**
Remember: Testing is the future, and the future starts with: you!

This should resolve the build issues in #192 and also close #193.

### CODE REVIEW

**Comment by franciscod** [comment]
:+1:

**Comment by StepS-** [comment]
Nice. :+1:

**Comment by mic-e** [comment]
I feel kind of bad for @schets for removing his whole `make_unique` code already; anyways, you can't stop progress.

**Comment by janisozaur** [comment]
> To boldly go…

Bravo!

**Comment by fr3akout** [comment]
:+1:

**Pull request merged**
