### PR TITLE
stemplet-dat.md: add information, clarify int size

### PR DESCRIPTION
**Pull request by Dico200**

### CODE REVIEW

**Comment by Dico200** [comment]
Please try squashing the commits. Sorry.

**Comment by Dico200** [comment]
https://github.com/aap/aoetwols/blob/master/aokbase.h#L219

**Comment by Dico200** [comment]
I think the drop down arrow next to the merge button let's you merge and squash

**Comment by TheJJ** [comment]
Indeed, that's even easier in this case! Merged.

**Pull request merged**
