### PR TITLE
Changed FAQ bullets to subheadings

### PR DESCRIPTION
**Pull request by frickler01**
Explanation of a bullet point was in a paragraph, now it's the block below a subheading - makes more sense IMHO.

### CODE REVIEW

**Comment by TheJJ** [comment]
Thanks. I think it'll look better with level 4 or more, what do you think?. Also please leave a space after the `#`s.

**Comment by TheJJ** [comment]
Alternatively, because i think subheadings won't look as cool as bullets, the answers to these questions could also be a `*`, but with two spaces indent so they're a subitem to the question.

**Comment by frickler01** [comment]
Since the current `h3` font size is only one possible representation, I'd prefer to mark it up semantically as the next subdivision of a given topic. When you introduce a new layer between these, just move the questions down one `#`.
Also having kind of real sentences as answers (instead of bullets) seems more considerate of the reader.

**Comment by TheJJ** [comment]
These texts are way too big then in my opinion.

About real sentences: I think full sentences are the one of the main reasons why people don't read readme text. The information needs to be trimmed out, nobody wants to read text blocks in man pages or readmes.

**Comment by TheJJ** [comment]
How do you like https://github.com/TheJJ/openage/blob/logo/README.md ? Including your logo :grinning:

**Comment by frickler01** [comment]
Thant works as well.

**Pull request closed without merging**
