### PR TITLE
Fix a typo in ideas/gameplay

### PR DESCRIPTION
**Pull request by steelbrain**
Just like the title says

### CODE REVIEW

**Comment by franciscod** [comment]
I think the `!!!111` is intentional, see this: http://urbandictionary.com/define.php?term=!!!111oneone

**Comment by steelbrain** [comment]
Well, you **think** that, I would change it back on a confirmation

**Comment by franciscod** [comment]
¯\_(ツ)_/¯

**Comment by TheJJ** [comment]
Jup, it's intended of course, thanks for the link @franciscod :D

**Comment by steelbrain** [comment]
@TheJJ Done

**Comment by TheJJ** [comment]
Might it be possible that you meld those two commits so that only the typo fix remains? Also, please remove the emoji in the commit message as it will only be displayed on github in a graphical way.

**Comment by steelbrain** [comment]
@TheJJ Done

**Pull request merged**
