### PR TITLE
[WIP] add quit button in menu mode

### LINKED ISSUE #616: Add quit button
One should be able to quit the game by pressing an exit button. This shall be done in the menu mode.

### PR DESCRIPTION
**Pull request by Shalzz**
fixes #616 

Just, can't seem to find the correct sender.

### CODE REVIEW

**Comment by Shalzz** [comment]
Any pointers?

**Comment by TheJJ** [comment]
`0x7f2c5dee6000`, `0x00610020`, `0x7faaf2624030`, `0x7f4988191000`
I hope they help you.

**Comment by Shalzz** [comment]
Wow, they don't.

**Comment by ChipmunkV** [comment]
Nah, Qt is here just for fancy buttons. It can't kill the whole thing easily.

Our strategy is probably to use the STOP_GAME action, because it does quit now. Where to get the actions: see #605 (but it also uses whole arrays of actions, which is an overkill for the quit case; instead, just stick an invokable into `CreationMode` or add a `MenuMode` #617 and put it there).

**Comment by TheJJ** [comment]
Thank you for the attempt. If you have updated code, please resubmit.

**Pull request closed without merging**
