### PR TITLE
Monk conversions instead of killings

### LINKED ISSUE #375: Monk kills enemy unit instead of converting to own team
and he doesn't keep distance to enemy unit.

### PR DESCRIPTION
**Pull request by bombadie**
I hope this fixes #375 
priests don’t get attack ability any more but instead convert ability. I also added a attribute remove function so that the owner attribute can be replaced. 
This is my first contribution so go easy on me :)

### CODE REVIEW

**Comment by TheJJ** [comment]
Thanks for the patches :)
Your commits aren't assigned to your github account, so either the mail in the commit is wrong or github doesn't know about it.

Also, I fear you have to do a rebase (see contributing.md or ask me) as the copying.md contains conflicts.

The code looks very good so far (haven't tested yet) apart from some indentation and formatting errors (you might want to turn on whitespace highlighting).

Currently, this is bound to the monk unit class, which is ok, but in the future we may extend the ability check for some gamespec attribute. Monk is ok for now, though.

**Comment by bombadie** [comment]
ok i added the used email address, did a rebase and looked though the files for whitespace errors. 
I hope everything is fine now

**Comment by TheJJ** [comment]
Uh i just tried it with a `RMONK0` to `9` and it didn't work, the monk killed the villager.

**Comment by bombadie** [comment]
Oh ok i just tried it too and RMNK0 to 9 really kill units. I've always used MONKX for trying it out and it works fine. What's the difference between these types?

**Comment by TheJJ** [comment]
No idea, do you notice any pattern in the data files? (`gamedata-empiresdat/0000-civs/0001/living.docx`)

**Comment by bombadie** [comment]
MONKX, MONKY, HARCH, HIMAM and HPOPE are unit_class PRIEST
RMONK and RMOK1 to 9 are unit_class MONK_WITH_RELIC
I tried to give RMONK convert ability too, but apparently they have a  attack_range of almost 0. This makes sense since monks with relics cant convert or heal units.

**Comment by TheJJ** [comment]
Okay, good. But my RMONK didn't have a visible relic? I remember that the unit graphic contained the reliq for carrying monks, so i wonder why it's the relic class but none is visible.

**Comment by bombadie** [comment]
Yeah its a little bit strange. RMONK does have a relic but RMNK1 to 9 doesn’t. Im not sure why there are so many RMNK without any relic, but i think that they aren’t normal monks because they have a villagers creation sound and a bigger selection radius.

**Comment by TheJJ** [comment]
Can you please do a rebase (see `contributing.md` or ask me on irc) to resolve the conflicts? We can merge it, and ignore the `RMONK0-9`s for now i'd say.

**Comment by bombadie** [comment]
Hey, sorry i have no idea why its not passing. It builds fine on my computer. Is it because i changed my email address?

**Comment by franciscod** [comment]
Having a look at the build (https://travis-ci.org/SFTtech/openage/builds/100911295) you can see this message:

```
WARNING author inconsistency: bayernsmacgyver@web.de
	email appears in git log, but not in copying.md or .mailmap
```

Also, this builds has MemorySanitizer complaining: https://travis-ci.org/SFTtech/openage/jobs/100911301

And this one says python3mu isn't found: https://travis-ci.org/SFTtech/openage/jobs/100911307

**Comment by TheJJ** [comment]
Hai! Can you please rebase in order to resolve conflicts and it is mergable again?
Also, the mail you used in the commits isn't associated to your github account. That's not critical, but otherwise your account won't show the contribution, so consider adding it.

**Comment by Vtec234** [comment]
Should this be closed with #789 in progress?

**Comment by TheJJ** [comment]
indeed :)

**Pull request closed without merging**
