### PR TITLE
[WIP] GUI

### PR DESCRIPTION
**Pull request by rkreis**
I started writing some GUI code (see #178) a while ago, but my efforts are currently on hold as I have too much else to get done.  I think the existing code is a good base for any future development, and already contains quite a bit of under-the-hood functionality.

If anyone is interested in GUI development, chat me up on IRC and I can walk you through the current architecture.  I hope to continue working on this myself "soon", but any contributors are welcome, of course.

### CODE REVIEW

**Comment by Jon0** [comment]
I am currently refactoring all the GameMain input handling. I should be able to merge with this after, and try make a game creation settings menu.

**Comment by Jon0** [comment]
Maybe a version of this without the changes to GameMain and Engine could be pulled, since the new files are the most important.

**Comment by jfeo** [comment]
I've been looking at your code a bit, and tried to make it work with the current master. I'm interested in working a bit on it, especially as it also kind of relates to #344

**Comment by TheJJ** [comment]
jfeo: go for it, we really need a proper gui. When you start, please use some centralized point where you do the opengl calls, as we will replace them to "render text and square" once the renderer (#287) is finished.

**Comment by TheJJ** [comment]
@jfeo i rebased the branch to my account on current master, but without the code in `game_main`. Maybe it's a starting point for further development :)

**Comment by ChipmunkV** [comment]
How about a Qt GUI for the ingame? QtQuick is pretty ready for that.

**Comment by TheJJ** [comment]
I'll close this for now, in favor of the Qt5 GUI.

**Pull request closed without merging**
