### PR TITLE
context_extraction osx patch

### LINKED ISSUE #585: Linking error building on OSX
make results in a linking error.

...
Undefined symbols for architecture x86_64:
  "qtsdl::extract_native_context(SDL_Window*)", referenced from:
      qtsdl::GuiRendererImpl::GuiRendererImpl(SDL_Window*) in gui_renderer_impl.cpp.o
ld: symbol(s) not found for architecture x86_64

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/35907308-linking-error-building-on-osx?utm_campaign=plugin&utm_content=tracker%2F371436&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F371436&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by vsimon**
Fixes #585

### CODE REVIEW

**Comment by ChipmunkV** [comment]
No way. And it works after that?

**Comment by vsimon** [comment]
The issue was about getting osx compiling without errors again. This does
that.

As far as osx "working" at runtime, I think there are other problems
separate from the compiling problems to be able to say 'everything works'.

**Comment by vsimon** [comment]
> And it renders the GUI correctly?

It doesn't get past the asset in extract_native_context: `assert(current_context);`. Again that should be a separate issue.

**Comment by ChipmunkV** [comment]
Yes, that function was written in the blind mode. Good that it compiles now.

Maybe `[NSOpenGLContext currentContext]` instead of `[NSGraphicsContext currentContext]` will get it past the assert.

**Comment by vsimon** [comment]
Thanks, I'll give that a shot. In the meantime, filed Issue #588.

**Pull request merged**
