### PR TITLE
Show current and required media version

### LINKED ISSUE #615: Show current and required media version
When a new media version is required, it just says "hey, reconvert" currently.
It should display the found media version and the new required version and what is going to be converted ("interface", "sound", ...).

### PR DESCRIPTION
**Pull request by kev946**
Fixes #615

### CODE REVIEW

**Comment by kev946** [comment]
I'm not sure if this is what we want

**Comment by TheJJ** [comment]
I think this is a bit too complicated, but also not bad. I was more thinking of a message like "found media of version x, but now we need version y, which is why we need to convert {...}". The version of each component isn't relevant for the enduser and also not for debugging.

**Comment by kev946** [comment]
Ok I'll make those changes when I get a chance

**Comment by kev946** [comment]
example output:
INFO [py] Found converted assets with version 2, but need version 4
INFO [py] Converting interface

**Comment by TheJJ** [comment]
merged with ca11d8f

**Pull request closed without merging**
