### PR TITLE
[WIP]coords with c++ templates

### PR DESCRIPTION
**Pull request by spjoe**
Instead of using macros and out of place `#include` I introduced c++ templates to create easily new coord types.

Cons
* construtor is not a constexpr constructor anymore :-1: 
* lot of code due to limitation on partial template specialization on methods :-1:

Pros
* no wired `#include` and `#defines` :+1:

Actual I am not really convinced anymore if this was the right call to do it with c++ templates. maybe code generation is better :). Or if somebody knows todo this c++ templates better (I wanted to use the  [get&lt;N&gt;](https://github.com/SFTtech/openage/compare/master...spjoe:feature/coord-template?expand=1#diff-19f485c287b0e7d5dede1d170aabae03R17) method on xyz_coord but the compiler did not let me, due to limitations partial template specialization on methods). 

e.g.
```cpp
template <typename AT, typename RT, typename ST, unsigned int N>
RT absolute_xyz_coord<AT, RT, ST, N>::as_relative() const {
        RT retval;
        for (unsigned int i = 0; i < N; i++) {
                retval.get<i>() = this->get<i>();
        }
        return retval;
}
```
Compiler should be able to do unrolling at compile time (N is known).

### CODE REVIEW

**Comment by TheJJ** [comment]
Hmm, this is _much_ more code for the same functionality as before. I'd say we should either use code generation or somehow clarify the `#define` hell that, yes, should be avoided.

The main thing that has to be improved is to no longer have global state (e.g. the camera position).
For those ideas, see (and discuss in) #56 please.

**Comment by TheJJ** [comment]
Do you plan on continuing this? Otherwise, I'll close this and somebody else might give it a shot.

**Comment by spjoe** [comment]
Sorry no time at the moment and I will not continue with it.

**Comment by TheJJ** [comment]
Ok. I'll close this now, but we can always dig it out again. Thanks for the attempt, though.

**Pull request closed without merging**
