### PR TITLE
Changed the copyright date to 2016

### PR DESCRIPTION
**Pull request by kilbyjmichael**
I don't know if this is actually helpful, but I felt like contributing something.

### CODE REVIEW

**Comment by TheJJ** [comment]
You need to add yourself to `copying.md` in order to pass the test :)

**Comment by kilbyjmichael** [comment]
Darn it, I forgot to add that file to the commit!

**Comment by kilbyjmichael** [comment]
Alright, I think I added it correctly. Did I break anything with the other merge of master commit?

**Comment by TheJJ** [comment]
Aaand now please do a rebase (see `contributing.md` or ask me on irc if you got problems) to purge the merge commits. You're nearly at the goal :goat: !

**Pull request merged**
