### PR TITLE
Documented usage

### PR DESCRIPTION
**Pull request by dbrgn**
Couldn't find this when trying the game :)

### CODE REVIEW

**Comment by charlesrgould** [comment]
Thanks, I was looking for this. Didn't know about the backtick. :)

**Comment by franciscod** [comment]
:+1: :D

**Comment by TheJJ** [comment]
awesome. we probably can remove status.md and create a real changelog instead now that we have this guide.

**Comment by dbrgn** [comment]
> Thanks, I was looking for this. Didn't know about the backtick. :)

Fun thing is, the backtick doesn't work on a Swiss keyboard, because backtick is a deadkey by default :)

**Pull request merged**
