### PR TITLE
renderer/color: cleanup

### PR DESCRIPTION
**Pull request by stiopaa1**
-remove copy constructor and assignment operator(default ones are fine)
-change operator!= to use operator==

### CODE REVIEW

**Comment by stiopaa1** [comment]
Oops, missed the copying.md part - sorry!

**Comment by TheJJ** [comment]
Just look at the CI output, you'll see the problems :)

**Comment by TheJJ** [comment]
Then I guess your browser is too old, you can peek into the F12-console and look for errors.

Here's the relevant output that you would see in Kevin-CI:
```
[sanity_check]
$ make checkall
python3 -m buildsystem.codecompliance --all

------------------------------------
Your code has been rated at 10.00/10

WARNING Bad copyright year: libopenage/renderer/color.cpp
	Expected 2017
	Found    2016

WARNING Bad copyright year: libopenage/renderer/color.h
	Expected 2017
	Found    2016

==> 2 issues were found.
make: *** [Makefile:130: checkall] Error 1
command returned 2

```

**Comment by Seadragon91** [comment]
I have the same problem, I have google chrome and its updated. In firefox it works, there I see the output.

**Comment by Seadragon91** [comment]
This is the error I see in the console:
```
WebSocket connection to 'ws://ci.sft.mx:7777/ws?project=openage&hash=25981e3bb86a55c56ea91cb470ff58efb4e84d83&filter=arch' failed: Error during WebSocket handshake: Sent non-empty 'Sec-WebSocket-Protocol' header but no response was received
```

I am not really sure, but maybe it's a problem with the response packet from the web socket.
This could help: https://github.com/mqttjs/MQTT.js/issues/408#issuecomment-221709738

**Comment by stiopaa1** [comment]
@Seadragon91 
Same here. Doesn't work on Chrome(checked 2 different PCs with different Linux distro), but works fine on Firefox.

**Comment by TheJJ** [comment]
I committed SFTtech/kevin@6547976cbadb29d7a4f98b9379d3bcaba6fa91a2 which should fix the problem. Try viewing on Chrome/Chromium again please :)

**Comment by Seadragon91** [comment]
Yay, it works now. Did a hard reload of the web page (ctr l + F5).

**Comment by stiopaa1** [comment]
Yep, works for me as well.

**Pull request merged**
