### PR TITLE
update macOS ci config

### LINKED ISSUE #1295: Fix macOS CI
Currently the github macos ci is broken: [example](https://github.com/SFTtech/openage/pull/1293/checks?check_run_id=1024044957). This should be fixed.

### PR DESCRIPTION
**Pull request by TheJJ**
pls work
fixes #1295 

closes #1238

### CODE REVIEW

**Comment by TheJJ** [comment]
It's getting way further now, but apparently `png.h` is not included, so the `struct png_image` is unknown.

**Comment by TheJJ** [comment]
png header still not included i think, even after merging #1301.

**Comment by simonsan** [comment]
https://github.com/SFTtech/openage/pull/1238

**Comment by simonsan** [comment]
I meant you are probably better off to use #1238 and change a bit there, because it is already optimized for caching and compresses homebrew stuff etc. Also this PR here shouldn't close #1238 because this one lacks 60-80% of the functionality of the PR you would close, which makes no actual sense to me. :-D

**Comment by TheJJ** [comment]
seems like the png version does not match. but homebrew says it has 1.6 installed:
```
brew install libpng
Warning: libpng 1.6.37 is already installed and up-to-date
To reinstall 1.6.37, run `brew reinstall libpng`
```

`./configure` fails:
```
CMake Error at /usr/local/Cellar/cmake/3.18.1/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:165 (message):
  Could NOT find PNG: Found unsuitable version "1.4.12", but required is at
  least "1.6" (found /usr/local/lib/libpng.dylib)
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.18.1/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:456 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/Cellar/cmake/3.18.1/share/cmake/Modules/FindPNG.cmake:156 (find_package_handle_standard_args)
  openage/convert/service/export/png/CMakeLists.txt:1 (find_package)
```

**Review by heinezen — DISMISSED** [review]
Should be good to go :)

**Review by heinezen — DISMISSED** [review]

**Review by heinezen — APPROVED** [review]

**Comment by heinezen** [comment]
:tada

**Pull request merged**
