### PR TITLE
[WIP] media version detection

### PR DESCRIPTION
**Pull request by zuntrax**
WIP. Do not merge yet.
This is just for easier progress tracking.

### CODE REVIEW

**Comment by franciscod** [comment]
nice!

**Comment by goto-bus-stop** [comment]
<3

It seems to mostly work on HD, aside from the empty `.drs` file (see #269). Is anything blocking this still?

**Comment by zuntrax** [comment]
I talked to JJ, this probably will not cut it. We will need proper supersedence rules and stuff, also JJ would prefer function objects over categories to determine what happens to the files.

**Comment by mic-e** [comment]
#288 will have some key components for this.

**Comment by TheJJ** [comment]
you probably wanna start from scratch with this as the new project layout and python interface is there now.

**Comment by mic-e** [comment]
I'd rather say: no longer applies, superseded by fix for #318.

**Pull request closed without merging**
