### PR TITLE
Add asset downloading guide to media_convert doc

### PR DESCRIPTION
**Pull request by paulirish**
Docs inlined from https://gist.github.com/paulirish/758f262379092ff2910a
Technique comes from https://github.com/dotfloat/steam-appmanifest

### CODE REVIEW

**Comment by janisozaur** [comment]
There is also a way of downloading raw depots when you launch steam with `-console` option.

Check https://steamdb.info/app/221380/depots/ for depot information.

```
$ steam -console
steam> download_depot <app_id> <depot_id> # app_id = 221380
```
there are multiple depots for a game possible, steam usually packages languages into depots, you need to download all the depots you need.

To download the main content, you would use:
```
steam> download_depot 221380 221381
```

See guide I wrote for another project: https://github.com/OpenRCT2/OpenRCT2/wiki/Installation-on-Linux#native

**Comment by TheJJ** [comment]
@paulirish do you also wanna add the steamcmd stuff @janisozaur said or should i merge the pullrequest now?

**Comment by paulirish** [comment]
Yeah I'll add in that technique too. Tested it and it looks good.

**Comment by TheJJ** [comment]
Are you still working on the second technique? Otherwise I'll merge the new guide.

**Comment by paulirish** [comment]
Not going to get a chance to properly include it, so yeah, go ahead and merge. 

cheers

**Pull request merged**
