### PR TITLE
[WIP] Map Engine

### PR DESCRIPTION
**Pull request by timohaas**
# Map Engine

moved map creation from the main loop to a new subsystem.
Created Interface for different map engines.
Implemented Engines:
* static: returns Grass map
* mandelbrot: returns Island of the shape of the mandelbrot set
* diamond square
* perline noise: true infinite random map possible

### CODE REVIEW

**Comment by detrumi** [comment]
It would've been nice if this was communicated better, as I've merged part of this PR into [one of my branches](https://github.com/detrumi/openage/tree/random-maps) (by your request). I'm fine with you working on it or taking it over.

On the perlin noise: someone already has implemented [a prototype](https://github.com/SFTtech/openage/pull/179) for this, though I'm not sure what the status on that is, and whether it's easy to call the python code from cpp code (this is also being worked on, but that's not finished yet).

**Comment by TheJJ** [comment]
Did you have a look at #179? It implements the noise generator in python, the API (#217) is close to being finished, so you can use the python implementation for the mapgen or even implement the mapgen in python itself (as it's not a time-critical operation).

I'd rather not add `libnoise` as a dependency, it doesn't seem to be widely available (at least missing in gentoo) and is very outdated (last commit 9 years ago..).

I like your modular approach, the code needs better integration though (we have an awesome logger e.g.). Keep up the good work, much potential is there, we'll come up with some nice ideas.

**Comment by timohaas** [comment]
@detrumi I'm sorry, I should have said something, but @TheJJ stated (https://github.com/detrumi/openage/pull/1#issuecomment-100703842), I should use the Master Repo for Pull Requests.
How should I proceed from here? Pull request to detrumi (original author of the branch) or to master Repo?

I didn't noticed the python implementation. I will have a look into it and use it to reduce the dependency.

**Comment by detrumi** [comment]
Go ahead with this PR to the master repo.

In my branch, I was just experimenting with the diamond-square algorithm, it's not finished yet. It's not flexible enough for map generation, though it may possibly be useful for generating the heightmap if we're implementing elevation.

**Comment by zuntrax** [comment]
@detrumi I think #179 should work for producing perlin noise. @rkreis claims that it actually produces value noise, not perlin noise. I wanted to verify my code and discuss it with him, but I didn't get to do it yet.

**Comment by rkreis** [comment]
No, I do believe it's perlin noise.  The noise in my test pictures is value noise, that's why it looks different from the in the PR.  I see nothing wrong with the noise generator the way it's in the PR.

**Comment by franciscod** [comment]
mandelbrot!!!

**Comment by timohaas** [comment]
Mandelbrot:
16 tiles per side
mandelbrot_16_tiles
32 tiles
mandelbrot_32_tiles
multiple 16 tiles per side chunks
mandelbrot_16_tiles_multiple_chunks
perlin: multiple 16 tiles per side chunks
perlin_16_tiles

**Comment by franciscod** [comment]
that is awesome!!! :D

**Comment by zuntrax** [comment]
@rkreis ah ok, then i just got your comment wrong.

**Comment by TheJJ** [comment]
Before it's too late, i'm really don't like bundling libraries in our code. Using "well-known" and up2date libs shipped with distros as new dependencies is much better. If no matching lib is available, we should (e.g. like the rng) implement stuff in "our way" so we have a simple-stupid awesome implementation written and maintained by the project itself.
That means, the best solution may be to either reimplement the perlin noise py code we already have in c++ or try to come up with some api that will then be provided by the py-api.

My suggestion: write the code in c++ and I'll replace it with the python part when the api is ready.

**Comment by timohaas** [comment]
You're right, this is an intermediate solution. I want a working travis ci build, so i can go on to the next working one.

**Comment by mic-e** [comment]
@timohaas: It should be rather simple; just have a look at `.travis.yml`; it's rather self-explaining. You'll probably simply need to add `libnoise-dev` or something like that to the install list.

**Comment by timohaas** [comment]
It's building now (Commit 478d227). I added the needed Header and Source Files directly to the Source Code. 

TheJJ  suggested, we implement our own Perlin Noise. I will look into this if needed, but would rather use the http://libnoise.sourceforge.net/ lilbrary. 
Debian has the lib in its repo (https://packages.debian.org/jessie/libnoise0).

**Comment by TheJJ** [comment]
The python interface is complete now, you can use parts the noise implementation commits from #179 i hope.

**Comment by zuntrax** [comment]
I'm the one working on the perlin prototype. I'll try to get this productive asap.

**Pull request closed without merging**
