### PR TITLE
Adding FreeBSD support

### PR DESCRIPTION
**Pull request by devnexen**

### CODE REVIEW

**Comment by castilma** [comment]
please add yourself to copying.md and update the copyright year in libopenage/util/pty.h.

**Comment by TheJJ** [comment]
Ah, now there's a conflict in `copying.md`, sorry. Please rebase to resolve the conflict.

**Comment by TheJJ** [comment]
thx :)

**Comment by TheJJ** [comment]
Maybe as a follow-up task, do you wanna add some documentation about how to build openage on freebsd?

**Comment by devnexen** [comment]
Sure why not :)

**Pull request merged**
