### PR TITLE
Conversion: support for some uppercase file names

### PR DESCRIPTION
**Pull request by goto-bus-stop**
The AoK:TC Collector's Edition has uppercase folder and file names for a bunch of base game files. (i.e. AoK, not AoC files.)

This attempts to fix with a different approach than #55, by just special casing for the uppercase names in addition to the normal names.

Supports `DATA/` in addition to `Data/`, and `LANGUAGE.DLL` in addition to `language.dll`.

I only this with my AoK-only disk, which also has those uppercase names, but they might not quite be the same on the Collector's Edition. So if somebody with a CE disk could confirm, would be much appreciated :)

### CODE REVIEW

**Comment by LordAro** [comment]
should use .format() rather than %, surely?

**Comment by goto-bus-stop** [comment]
Probably, but I went with `%` because that's what the rest of the convert script uses

**Comment by TheJJ** [comment]
Thanks for another attempt of hardcoding version diffferences :smile: .
Please meld the commits, after that we can merge the pull :+1:

**Comment by goto-bus-stop** [comment]
Maybe @Almin17 can confirm if this works on their Collector's Edition version too, before merging?

**Comment by Almin17** [comment]
Yes, it does work!

**Comment by StepS-** [comment]
My data directory is all-lowercase "data" instead. Shouldn't there be an unified way to fix these things?

**Comment by franciscod** [comment]
ciopfs, lol

**Comment by goto-bus-stop** [comment]
@StepS- Yes, in #55. I guess that might be a better option after all.

**Pull request closed without merging**
