### PR TITLE
Use Mako instead of Jinja2

### LINKED ISSUE #1273: Replace jinja2 with mako
Due to personal experience I'd really like to replace jinja2 with mako templates instead.

We only use jinja in `openage/codegen/coord.py`.

Really not high priority :)

### PR DESCRIPTION
**Pull request by zoli111**
Pretty descriptive title. This closes #1273.

### CODE REVIEW

**Review by heinezen — CHANGES_REQUESTED** [review]
Code looks good and works like a charm :)

The only thing you still have to do is pass the code checks. Simply run `make checkall` and fix the things it complains about. Our CI does not have `mako` yet, so don't worry about the red Xs on GitHub.

**Comment by zoli111** [comment]
Done. I fixed all the warnings for the files I changed.

**Review by heinezen — APPROVED** [review]

**Comment by heinezen** [comment]
LGTM :)

**Review by TheJJ — APPROVED** [review]
nice! very glad to get rid of jinja, i like mako so much more :)

**Comment by TheJJ** [comment]
Okay, the ci build now basically works, but there's some errors left, which seem unrelated to your changes and due to updates in the CI environment.

**Comment by zoli111** [comment]
I'm glad I could help :)

**Pull request merged**
