### PR TITLE
add forgotten line separators in csv output

### PR DESCRIPTION
**Pull request by rkreis**
for example .slp.docx

### CODE REVIEW

**Comment by franciscod** [comment]
context please?

**Comment by TheJJ** [comment]
this function creates comment lines for generated code.

i forgot to add the newlines by which the text block was split up before, but probably nobody noticed so far as i can't remember to use any multiline comment so far.

**Comment by franciscod** [comment]
:+1:

**Comment by TheJJ** [comment]
uh yeah i forgot my :+1:

**Pull request merged**
