### PR TITLE
Ignore 'Bin' directory if non-existent

### PR DESCRIPTION
**Pull request by dopsi**
In my installation the 'Bin' directory does not exist, however everything runs fine.
Does this cause any trouble ?

### CODE REVIEW

**Comment by zuntrax** [comment]
Which version of AoE2 do you have? If it's the HD edition, you should have a `Bin` directory. Assuming you didn't tamper with the original file structure and get errors during media conversion, something weird might be going on. I'd like to see a `ls -l` of your `AGE2DIR`
@TheJJ are we aware of cases where `language.dll` is missing in non-HD installations?

The code block you edited will be removed in #237 and #238 and replaced by a more sane version detection. However, you would probably still get an exception because your files don't match what we expect.

The only thing we export from the `Bin` directory are the language files, but afaik we don't use them on the master branch. That's why you don't get errors this way, but as soon as we start displaying unit names or similar stuff, you would run into problems anyway.

**Comment by goto-bus-stop** [comment]
If your language file is called eg. `LANGUAGE.DLL`, the script won't find `language.dll`, and assume HD Edition. See #55…

**Comment by zuntrax** [comment]
That might indeed be the cause.
Seems like I'll have to write some case-insensitive file access helper functions. :fu:

**Comment by TheJJ** [comment]
Hnnng case sensitivity.. :cactus: -> :point_up: -> :astonished:

A solution could be:
* listing all files in a relevant directory
* index them by number
* make a copy of the `idx->filename` dict and do  `.lower()`,
* select the one we wanna have
* and return the actual filename by index

This will probably be readable and portable.

**Comment by TheJJ** [comment]
I'm just implementing such a function, eta 20min.

**Comment by zuntrax** [comment]
Something like that, but we'd also need to reproduce the functionality of `glob.glob()`. `fnmatch` will help, but i don't look forward to it.

**Comment by dopsi** [comment]
Here's the `ls -l` output : http://pastebin.com/vXtacALr
I did not mess with the hierachy, just copied it from my win7 partition to my home.

**Comment by goto-bus-stop** [comment]
@dopsi For the time being, you can rename LANGUAGE.DLL to language.dll, and you should be good to go.

**Comment by TheJJ** [comment]
My attempt is #248 for this, please try whether it works.

**Pull request closed without merging**
