### PR TITLE
improved shader for team colors

### PR DESCRIPTION
**Pull request by ptolstoi**

### CODE REVIEW

**Comment by fr3akout** [comment]
Please fix your legal headers, such that `make checkfull` doesn't report any errors and the Travis CI build succeeds.

**Comment by ptolstoi** [comment]
fixed

**Comment by TheJJ** [comment]
I think this is ready for merge, but we have to keep #204 in mind. Otherwise many users will totally get confused why the game looks wrong for them after this is merged.

**Comment by ptolstoi** [comment]
there is a new one ;)

**Pull request closed without merging**
