### PR TITLE
fancy new logo!

### PR DESCRIPTION
**Pull request by TheJJ**
yay! finally some logo!

@frickler01 please provide me your real name and some actual email so i can update the commit author to you.

btw i have no idea how the readme will display the logo, but we'll see that in a minute.

### CODE REVIEW

**Comment by franciscod** [comment]
https://github.com/SFTtech/openage/issues/285#issuecomment-114790988

@TheJJ you might have wanted to mention @linkmauve instead of @frickler0

**Comment by detrumi** [comment]
@franciscod: We mentioned @frickler01 because he's the one who made the logo. @linkmauve only changed a small bit of it.

Though I'm not sure it's a good thing to set the commit's name to someone else's.

**Comment by franciscod** [comment]
contributors.md needs him too!

**Comment by mic-e** [comment]
What about this?

**Comment by boombatower** [comment]
logo++

**Comment by TheJJ** [comment]
The problem is that github doesn't support rendering repo-relative svgs, why ever.

>

> Hi JJ,
> Thanks for getting in touch! There's nothing amiss with your markup -- It's not currently possible to render relative SVG images in Markdown on GitHub. I believe it's set up this way to block a potential security vulnerability, but I'll certainly let the team know you'd like to see relative SVG image rendering enabled in the future if possible. 

>

**Comment by charlesrgould** [comment]
Try [RawGit](http://rawgit.com) to serve the banner?

Example:
https://cdn.rawgit.com/TheJJ/openage/98abfcda1b1c3d17a096886804bd96215bf74261/assets/logo/banner.svg

**Comment by TheJJ** [comment]
two problems with that:
0. it's not repo-relative then. if you update the image, it should be updated in your readme as well
1. it doesn't support the `xlink` in there. to avoid redundancy, the banner includes the logo image.

**Comment by TheJJ** [comment]
>> Can you please add support for placing svg images in readme files?
>
>This is currently disabled for security reasons. We hope to enable it again soon, but I don't have a date that I can give you, unfortunately. I'll pass your feedback onto the team though.

**Comment by TheJJ** [comment]
>> What security reasons? You already render the svgs in the image viewer,
>> why don't apply the security reasons there?
>
>As far as I'm aware, directly embedding from within the repo was disabled due to the fact that SVGs can contain JS scripting that would then have access to our fileserver. To prevent this, we serve all files with that capability as plain-text when accessed directly from the repository.
>
>Embedding from an external site such as rawgit.com means that if there was scripting, it would not have direct access to our server. Same thing for serving them in the image viewer, which uses a different domain that's responsible for rendering more complicated files.
>
>I know this isn't ideal, and like I said before, we're working on finding more secure ways to render these files relatively. I'll pass your concerns on to the team working on it. Thanks for taking the time to write in!

**Comment by TheJJ** [comment]
What do you think? https://github.com/TheJJ/openage/blob/logo/README.md

**Comment by charlesrgould** [comment]
Looks good on desktop and mobile.

**Pull request merged**
