### PR TITLE
Reverse engineering: describe some specific SWGB mechanics [v2]

### PR DESCRIPTION
**Pull request by MayeulC**
Sorry for not working on this for a long time, I just got my desktop computer back.

On the other hand, I also heard of hacktoberfest in the meantime, so I hope you won't mind my opening a new PR instead of pushing to #1293?

This addresses the feedback I received. I ended up adding some screenshots from the net for the UI, unfortunately those are of varying quality, but should qualify as fair use.

I'll try to boot up the game under Wine at some point (it doesn't work out of the box), and collect additional feedback. I don't know if you want this merged as-is, or without the screenshots?

Obviously, both commits are intended to be squashed, I separated them to ease the review. I can squash and re-push if you prefer.

Closes #1293.

### CODE REVIEW

**Review by heinezen — DISMISSED** [review]
LGTM :)

**Comment by MayeulC** [comment]
Nice, thanks :tada: 

Rather unexpectedly, I was about to boot up swbg for the first time since a long time right now.
I'd like to update the screenshots before you merge.

I tried to make sense of the shield mechanisms, but haven't collected enough data:

- shield depletion rate seems to be about 1000/35s for structures, and 35-40hp/s for units. i need to conduct more robust testing on this.
- it is not the same refill rate for every structure or units, therefore I am guessing something like a % per sec: I cut the shield for a lot of structures at once, then re-enabled it. Seemed like structures with more HP had a full shield quicker.

I'd like to devise a plan to compute all of that, but let's merge the basic description first, I'll add the above findings as well.

**Comment by heinezen** [comment]
Yeah, you can update them if you want. And squashing would be good :)

I do not have a lot of time for extensive testing of SWGB right now, so if you want to investigate depletion rates that would be great!

**Comment by TheJJ** [comment]
bumpity bamp? :)

**Comment by MayeulC** [comment]
Wow, thanks for the bump, I thought this had been merged. I think I have local commits/screenshots I'll push, I must've been sidetracked at some point.

**Review by heinezen — APPROVED** [review]

**Comment by heinezen** [comment]
I'll merge this for now because it is much more useful in the repo than in the PR :D

@MayeulC You can add the other changes in a new PR

**Pull request merged**
