### PR TITLE
[WIP] Debian packaging

### PR DESCRIPTION
**Pull request by ChipmunkV**
Uses `git-buildpackage`. Packaging files are on a separate branch. master is merged into that branch to make a release. (so, this pull request is not for master, but for the debian branch or maybe a separate packaging repo)

```
# vars
DEBEMAIL="velorums@gmail.com"
DEBFULLNAME="velorums"
DEB_BUILD_OPTIONS="parallel=4"
export DEBEMAIL DEBFULLNAME DEB_BUILD_OPTIONS

# https://github.com/SFTtech/openage.git has 'master' and 'debian' branches
# 'master' won't contain any debian packaging-related files

# building a package
git checkout debian
gbp buildpackage

# making a new version
git checkout master
echo v0.3.2 > openage_version
git commit -m"Bumped version number to 0.3.2" openage_version
git tag v0.3.2
git checkout debian
git merge master
vi debian/changelog # add the version and a comment (TODO: 'gbp dch' may generate that)
git commit -m"changelog to 0.3.2" debian/changelog
```

### CODE REVIEW

**Comment by TheJJ** [comment]
I'd go for a separate packaging repo, we wanted to avoid any branches except some lts-versions in the future. How should I name it? openage-debian? Can it live without the source files and just be that debian folder?

**Comment by ChipmunkV** [comment]
openage-debian is ok (with just a master branch for `debian/`).

Just a debian dir may work (with some changes to the config and the procedure) if the upstrem is tagged correctly and if it doesn't break any other gbp utilities that may be useful.

It should be Ubuntu-compatible for version >=15.10 (because of cython build dependency).

Need to fix a dozen of packaging warnings. Also, the `*.desktop` file and installed pycache dirs look suspicious in openage itself.

I hope that PPA can be hooked up to some automatic build/release system, so the update of the version would be:

1. openage/master: commit version change to `openage_version`
2. openage/master: push tag with the version number
3. openage-debian/master: commit the change to the `debian/changelog`
4. ???
5. New version is added to PPA

**Comment by TheJJ** [comment]
I created a new repo at https://github.com/SFTtech/openage-debian

**Comment by TheJJ** [comment]
Can you submit your results to the packaging repo please? I can try uploading it to our PPA then.

**Comment by ChipmunkV** [comment]
This PR is superseded by https://github.com/SFTtech/openage-debian/pull/1 and https://github.com/SFTtech/openage/pull/557

**Comment by TheJJ** [comment]
kay :)

**Pull request closed without merging**
