### PR TITLE
Add ubuntu 22.04 to the build pipeline

### PR DESCRIPTION
**Pull request by timo-a**
This PR adds a build on ubuntu 22.04 to the github workflows.
This PR is also evidence that #1474 is solved (I haven't tried to build locally though, only fiddled with the yml files).

### CODE REVIEW

**Comment by duanqn** [comment]
Do you have a successful run for the new workflow somewhere?

**Review by duanqn — DISMISSED** [review]

**Comment by TheJJ** [comment]
thanks!
now that 22.04 works, i think we can remove 21.04, it won't be supported much longer anyway

**Comment by duanqn** [comment]
> thanks! now that 22.04 works, i think we can remove 21.04, it won't be supported much longer anyway

Agreed. :)

**Comment by timo-a** [comment]
> Do you have a successful run for the new workflow somewhere?

Yes, over at my fork: https://github.com/timo-a/openage/actions/runs/2405696342

**Comment by timo-a** [comment]
> > thanks! now that 22.04 works, i think we can remove 21.04, it won't be supported much longer anyway
> 
> Agreed. :)

I have removed 21.04 from the branch of the PR. 
(most recent successful run is now https://github.com/timo-a/openage/actions/runs/2411215395)

**Comment by heinezen** [comment]
@timo-a Great!

Can you also remove the references to old Ubuntu in the [build instructions](https://github.com/SFTtech/openage/blob/master/doc/build_instructions/ubuntu.md) with your PR. Because we don't need those anymore :)

**Comment by duanqn** [comment]
> @timo-a Great!
> 
> Can you also remove the references to old Ubuntu in the [build instructions](https://github.com/SFTtech/openage/blob/master/doc/build_instructions/ubuntu.md) with your PR. Because we don't need those anymore :)

You mean the Ubuntu 20.04 instructions?

**Comment by heinezen** [comment]
Good job!

**Pull request merged**
