### PR TITLE
New logging system

### PR DESCRIPTION
**Pull request by iNaKoll**
A new policy-based logging system.
See log_configure.h for the actual configuration and some examples.

### CODE REVIEW

**Comment by goto-bus-stop** [comment]
@TheJJ ping!

**Comment by TheJJ** [comment]
This is more or less good work, but @mic-e has been working on a logger for a long time(tm) and should finish his logger very soon. When both pulls are here, we should merge the best features of both logging systems.

**Comment by franciscod** [comment]
@TheJJ @mic-e 
*>very soon*
*>1mo ago*

**Comment by TheJJ** [comment]
He's actually working on that for nearly half a year now... @mic_e pls...

**Pull request closed without merging**
