### PR TITLE
Fix dead units receiving damage

### LINKED ISSUE #410: dead units receive damage
I noticed this when attacking the enemy TC with lots of archers, who currently do splash damage: When one of them is near to the TC center, where the arrows arrive, he is being damaged, and quickly dies. I had him selected at that point.
His corpse remains selected (white circle), and keeps its health bar, until it is decayed. The health bar grows unlimited from the "0" point to the left, when he receives further damage.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/28789912-dead-units-receive-damage?utm_campaign=plugin&utm_content=tracker%2F371436&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F371436&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by s4chin**
Fixes #410

### CODE REVIEW

**Comment by TheJJ** [comment]
looking good, simple and easy :+1: 

if i only had more pull requests this quickly to review ;D

**Comment by TheJJ** [comment]
gnargh, i fear you have to rebase (see `contributing.md` or ask me if you need assistance) and fix the conflict in the `copying.md`

**Comment by s4chin** [comment]
Done.

**Comment by TheJJ** [comment]
Thanks, good job :)

**Pull request merged**
