### PR TITLE
Fix Python styling issues

### PR DESCRIPTION
**Pull request by zoli111**
`make checkall` complains about missing spaces in some files. This PR adds them.

### CODE REVIEW

**Review by heinezen — APPROVED** [review]

**Comment by heinezen** [comment]
Thanks, looks like your pylint version is newer and has therefore more complaints :)

**Comment by zoli111** [comment]
At least you don't have to deal with this later :)

**Review by TheJJ — APPROVED** [review]
thx

**Comment by TheJJ** [comment]
what pylint version do you have?

**Comment by zoli111** [comment]
> what pylint version do you have?

2.17.5, the latest on Arch

**Pull request merged**
