### PR TITLE
Stub some unused, unimplemented stuff on WIN32 so it can compile

### PR DESCRIPTION
**Pull request by franciscod**
Cleaner, fresher form of #207. Won't harm current platforms :)

### CODE REVIEW

**Comment by TheJJ** [comment]
although stubbing stuff is probably the way to go for now, we might add plattform-specific demos and tests so that the incompatible functions don't even show up when under an incompatible plattform.

**Comment by franciscod** [comment]
We could have a cpp/crossplatform/os.h that simply does an include to os_apple.h or os_linux.h or os_windows.h, and the platform-specific .h and .cpp would have #ifdef PLATFORM :)

**Comment by franciscod** [comment]
We could have a cpp/crossplatform/os.h that simply selects os_apple.h or os_linux.h or os_windows.h, using preprocessor ifdefs and platform-dependant macros. With that scheme, the platform-specific .h and .cpp files would be clean of ifdefs :)

**Comment by TheJJ** [comment]
This also needs updating to the new buildsystem updates and project layout.

**Comment by franciscod** [comment]
I'll take a look :)

**Comment by franciscod** [comment]
okay this is now rebased on top of my [msys2 random tweaks pull request™](https://github.com/SFTtech/openage/pull/476)

I'd say we merge this so we have MSYS support ASAP, and then improve the stubs with the real functions.

Keep in mind these stubbed functions are not used in the game yet!

**Comment by franciscod** [comment]
oh i'm rebasing commits from a year ago and travis yells me "2016 is wrong, use 2015!!!"

**Pull request merged**
