### PR TITLE
Gui improvements

### LINKED ISSUE #611: Units can be selected through the UI
Units hidden behind the bottom UI can be selected and their health bars will appear.

## <bountysource-plugin>

Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/37970498-units-can-be-selected-through-the-ui?utm_campaign=plugin&utm_content=tracker%2F371436&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F371436&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by MaanooAk**
Some small gui improvements. There always have been those small gui things that make the first glance of the game little bit... so:

- Moved the unit info to the qml
- Cleaned the player name and abilty info
- Default debug overlay to invisible
- Slower fps updates so they are readable 

Screenshot from 2019-09-20 18-07-55

(Health bar is placeholder (next pr))

Edit (simonsan): Closes #611

### CODE REVIEW

**Comment by heinezen** [comment]
Nice!

**Comment by MaanooAk** [comment]
Ok, so added a image placeholder (and format better the info), but I am not sure from where to fetch the icons (is this even parsed?), anyone knowns? In any case we can leave the placeholder until nyan.

Screenshot from 2019-09-21 00-16-00

**Comment by simonsan** [comment]
@MaanooAk Really cool stuff! Just asking: Is there any issue with the [ui-label](https://github.com/SFTtech/openage/issues?q=is%3Aissue+is%3Aopen+label%3Aui) that could be referenced here or is maybe even already fixed by this PR/ or in general outdated?

**Comment by MaanooAk** [comment]
@simonsan I fixed the #611, the other are mostly suggestions and not bugs.

**Comment by simonsan** [comment]
> @simonsan I fixed the #611, the others are mostly suggestions and not bugs.
Nice, thank you for taking a look into that. 👍

**Comment by heinezen** [comment]
@MaanooAk The icons are in 50730.slp, but not cut out. I wouldn't worry about that until #1151 is ready.

**Comment by MaanooAk** [comment]
@heinezen Ok, at the moment a have the placeholder with `image://by-filename/converted/interface/50730.slp.png.2`, so they are somehow cut but the mapping of sprite location to unit type is probably missing. However #1151 should keep in mind that icons are needed

**Comment by sandsmark** [comment]
There are two slp/shp files you probably want to reference there eventually. btnunit.shp (50730) is for units, and ico_bld2.shp (50706, but there's 4 identical ones, iirc) is for buildings.

Eventually you probably want itemicon.shp (50731) as well, those are the icons for the amount of wood carried, armor, attack range etc.

The progress bar is in sundial.shp (50764), and if you want to make it really identical you should get unithalo.shp (unithalo.shp) as well, to display behind the unit icon.

The correct icon you get from the dat file, in genieutils it is `Unit::IconID`, which is the frame number in the SLP/SHP file.

References, in case I missed something (it's some time since I implemented it); https://github.com/sandsmark/freeaoe/blob/master/src/ui/UnitInfoPanel.cpp is the info panel itself, and here I collected all the filenames with IDs I've found; https://github.com/sandsmark/freeaoe/blob/master/src/resource/AssetManager.cpp#L400-L620

**Comment by MaanooAk** [comment]
@sandsmark HUGE help, thanks mate

Made the icon to be exported to the unit type and then made the gui actually showing the correct icon (and added the border from 53003.slp). And also added the team tag (Enemy, Ally or nothing) bellow the name and civ)

Screenshot from 2019-09-21 23-34-20

I think this is a good point for merge (progress and health bars next month...)

**Comment by heinezen** [comment]
@MaanooAk Looks fine :)

Keep in mind that a lot of the changes could become obsolete with the new nyan gamestate, so you might want to look out for that.

**Pull request merged**
