### PR TITLE
Update building.md

### PR DESCRIPTION
**Pull request by caschulz88**
Added Fedora 22 dependencies (switched from yum command to dnf)

### CODE REVIEW

**Comment by TheJJ** [comment]
Thanks! can you [meld the fixup commit into the previous one](https://github.com/SFTtech/openage/blob/master/doc/contributing.md#rebasing---what-the-hell-is-it-and-why-do-i-need-it) please? Otherwise (although i can't comfirm the command^^) it looks good.

**Comment by TheJJ** [comment]
I fear now that the opensuse changes were merged (#331) you have to rebase against the current master. If you need help with that, just ask.

**Comment by caschulz88** [comment]
Awww, I just rebased everything to the master and resolved the conflicts from the OpenSUSE commit. Too bad I forgot to read the first answer first :P So let me do another push ;)

**Comment by caschulz88** [comment]
All done :)

**Pull request merged**
