### PR TITLE
Fix some MSVC compiling issues

### PR DESCRIPTION
**Pull request by duanqn**
Fix [C4805](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-1-c4805) and C2416.

### CODE REVIEW

**Review by TheJJ — DISMISSED** [review]
thx

**Comment by TheJJ** [comment]
Do you wanna add more things or can I merge it?

**Comment by duanqn** [comment]
Sorry. Give me an hour or so. I probably should squash them into one commit.

**Review by TheJJ — APPROVED** [review]

**Comment by TheJJ** [comment]
thank you :)

**Pull request merged**
