### PR TITLE
[WIP] Fix paper crash

### LINKED ISSUE #577: Game crashes on pressing M | "Change Mode"
Whenever I try to change to action mode, the game crashes. Console output: 
```
Traceback (most recent call last):
  File "run.py", line 15, in init run (/home/lisacvuk/openage/run.cpp:882)
    main()
  File "/home/lisacvuk/openage/openage/__main__.py", line 94, in main
    return args.entrypoint(args, cli.error)
  File "/home/lisacvuk/openage/openage/game/main.py", line 43, in main
    return run_game(args, assets)
  File "openage/game/main_cpp.pyx", line 24, in openage.game.main_cpp.run_game (/home/lisacvuk/openage/openage/game/main_cpp.cpp:962)
    result = run_game_cpp(args_cpp)
  File "", line 0, in 
  File "", line 0, in openage::run_game(openage::main_arguments const&)+0x42d
  File "", line 0, in openage::Engine::run()+0x1f
  File "", line 0, in openage::Engine::loop()+0x3b7
  File "", line 0, in openage::util::gl_check_error()+0x12c
  File "", line 0, in openage::error::Error::Error(openage::log::message const&, bool, bool)+0x152
  File "", line 0, in openage::error::StackAnalyzer::analyze()+0xb6
  File "libopenage/util/opengl.cpp", line 66, in void openage::util::gl_check_error()
    throw Error(MSG(err) <<
openage.cppinterface.exctranslate.CPPException: OpenGL error state after running draw method: 1285
	out of memory, wtf?

```

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/35478415-game-crashes-on-pressing-m-change-mode?utm_campaign=plugin&utm_content=tracker%2F371436&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F371436&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by ChipmunkV**
(**edit:** actually, it's unrelated to #577).

Makes the paper more yellowish, but removes inline shaders that were causing problems when chained together by the untrained personnel.

Uses some copy-paste from Qt 5.7.

### CODE REVIEW

**Comment by TheJJ** [comment]
Mkay :) Aren't those qml files included in some package normally or is there a reason we need to copypaste them? I'd like to avoid it, but if you made changes or they aren't bundled somewhere else then be it.

**Comment by lisacvuk** [comment]
Does not work. At least not for my issue.

**Comment by TheJJ** [comment]
In my qt5.5 graphicaleffects package, the the invert property is missing, but we don't use it anyway i think. so we should be good with the default files?

```diff
jj@jjpad ~ % diff /tmp/OpacityMask57.qml /usr/lib64/qt5/qml/QtGraphicalEffects/OpacityMask.qml                                                               [0]:pts/7 
41a42
> import "private"
116,131c117
<     /*!
<         This property controls how the alpha values of the sourceMask will behave.
< 
<         If this property is \c false, the resulting opacity is the source alpha
<         multiplied with the mask alpha, \c{As * Am}.
< 
<         If this property is \c true, the resulting opacity is the source alpha
<         multiplied with the inverse of the mask alpha, \c{As * (1 - Am)}.
< 
<         The default is \c false.
< 
<         \since 5.7
<     */
<     property bool invert: false
< 
<     SourceProxy57 {
---
>     SourceProxy {
136c122
<     SourceProxy57 {
---
>     SourceProxy {
164,166c150
<                 gl_FragColor = texture2D(source, qt_TexCoord0.st) * ("
<                     + (invert ? "1.0 - " : "")
<                     + "texture2D(maskSource, qt_TexCoord0.st).a) * qt_Opacity;
---
>                 gl_FragColor = texture2D(source, qt_TexCoord0.st) * (texture2D(maskSource, qt_TexCoord0.st).a) * qt_Opacity;
```

Can't find `SourceProxy.qml` though.

**Comment by ChipmunkV** [comment]
@TheJJ, I've copies some sources from Qt 5.7 just for the new "invert" property.

Now I see that this fix is not related to #577.

**Comment by TheJJ** [comment]
Do we still need this? Shall we remove the inline shaders?

**Comment by ChipmunkV** [comment]
This PR is a bugix for a bug that wasn't encountered by anyone except me (and I can't reproduce it any more on current nVidia driver). It requires Qt 5.7, so it can wait.

**Comment by zuntrax** [comment]
Closing for now. Added label to easily find this later, should we need it again.

**Pull request closed without merging**
