### PR TITLE
Issue 282: fixed argument parser

### LINKED ISSUE #282: Argument parser is buggy
* `openage -t` crashes with
```
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_S_construct null not valid
[2]    24332 abort      ./bin/cpp/openage -t
```
* `openage -d` crashes instead of just echoing the `option requires an argument -- 'd'` (which happens a few lines earlier)
```
$ ./bin/cpp/openage -d
./bin/cpp/openage: option requires an argument -- 'd'
openage - a free (as in freedom) real time strategy game

usage:
    openage [OPTION]
available options:
-h, --help                              display this help
-t, --test=NAME                         run test NAME
-d, --demo=NAME [arg [arg [...]]]       run demo NAME
--list-tests                            print a list of all available tests
--version                               print the openage version to the console
--data=FOLDER                           specify the data folder

 ERR Error:  ERR cpp/args.cpp:127 (openage::Arguments openage::parse_args(int, char **), thread 0): Unknown argument: -d
CRIT Exception: Error:  ERR cpp/args.cpp:127 (openage::Arguments openage::parse_args(int, char **), thread 0): Unknown argument: -d
```
* same is for `openage --data` without passing a dir
* not a bug, but when you're on it: allow `-l` as a short option for `--list-tests`
* not a bug either, maybe you come up with a nice short option for `--data`

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/11396965-argument-parser-is-buggy?utm_campaign=plugin&utm_content=tracker%2F371436&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F371436&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by detrumi**
- Fixed crashes for missing arguments
- Added shorthand `-v` for `--version`
- Added shorthand `-l` for `--list-tests`
- Added some comments for clarity

Fixes #282

### CODE REVIEW

**Comment by detrumi** [comment]
Ah, the build failed because my name wasn't added to `copying.md` in this branch. I added my name to it in the `keybindings` branch, but that one isn't merged yet.

**Comment by franciscod** [comment]
you should add your name here too :) whichever one gets merged first will do it without conflicts, and the another will have resolved it (if you add the same line)

**Comment by detrumi** [comment]
It builds now :-)

**Comment by TheJJ** [comment]
nice, it's cleaned up now. :+1: merge!

**Comment by franciscod** [comment]
awesome :+1:

**Comment by detrumi** [comment]
Any reason this isn't merged yet? Or didn't you guys have time for this yet? I don't have push permission on the repo yet, so I can't do it myself.

**Pull request merged**
