### PR TITLE
Merging classes: GameMain+Engine = Game

### LINKED ISSUE #159: Slowly implement game_main mess as sane engine features
The `Game` object should be initialized directly from `int main()`, with `--no-video` and `--no-audio` arguments.
## <bountysource-plugin>

Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/6176887-slowly-implement-game_main-mess-as-sane-engine-features?utm_campaign=plugin&utm_content=tracker%2F371436&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F371436&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by franciscod**
Closes #159 

This had a few weeks, and I just rebased it to the latest master. Please review it!

I don't know if anything else is this missing, but feel free to take a look and suggest stuff!

### CODE REVIEW

**Comment by franciscod** [comment]
usual squash rebase is due, i left those split so the review is easier

**Comment by TheJJ** [comment]
This probably causes big breakage with #172, we should merge this after @jon0's stuff is upstream.

**Comment by franciscod** [comment]
definitely.

**Comment by TheJJ** [comment]
hm, having a look at it, it doesn't seem like a good idea merging the utterly broken `GameMain` with the hopefully clean `Engine`. The better way, as @mic-e hopefully meant in #159, is to migrate all the contents of gamemain to the engine class in a sane way.

All features instanced and "tested" in `GameMain` should become sane engine features someday. Just merging the contents directly doesn't address the actual problem.

**Comment by Jon0** [comment]
Seperation does make some sense. Think of the game menus being rendered before a game is started. The engine is always running to handle any kind of rendering (including ui / menus) even without a game, allowing you to start one game quit back to the main menu and then start a new game.

**Comment by franciscod** [comment]
Even if the patches are worthless, I'm glad they kickstarted this
discussion :D should we move it to the linked issue?

**Pull request closed without merging**
