### PR TITLE
convert: Check for game version in only one place

### PR DESCRIPTION
**Pull request by azrdev**
Introduce GameVersion enum, and store an instance once determined.
Everybody else can switch version-specific code upon it, instead of
reinventing the wheel

I'm using [enum](https://docs.python.org/3.4/library/enum.html), which is available as of python 3.4 - didn't find a note how backwards compatible you want to be.

### CODE REVIEW

**Comment by TheJJ** [comment]
Thanks! This is looking very good.

Unfortunately, some update to pylint now complains about all sorts of errors you aren't responsible for.
We'll fix them as soon as possible, and then ask you to rebase to include those changes.

No worries, i think your code looks fine and does good things :)

**Comment by TheJJ** [comment]
Please now rebase on the current master, I fixed the pylint problems in our upstream code :)

**Comment by azrdev** [comment]
@TheJJ rebased & improved my work. Once13014b9 survives CI, please merge!

**Comment by TheJJ** [comment]
Awsum! Thanks! Wheee!

**Pull request merged**
