### PR TITLE
Consolidate fedora build instructions into a single document

### PR DESCRIPTION
**Pull request by kev946**
Addresses #915

### CODE REVIEW

**Comment by TheJJ** [comment]
What do you think of removing the old versions and to write "Fedora >= 22"?

**Comment by kev946** [comment]
I think that it makes sense to write Fedora >= 22, because they've been unsupported for almost 2 years http://fedoraproject.org/wiki/End_of_life

**Comment by TheJJ** [comment]
Please also update the links to the renamed file, otherwise they'll orphan.

**Comment by kev946** [comment]
oops

**Pull request merged**
