### PR TITLE
Coordinate types pretty print

### PR DESCRIPTION
**Pull request by heinezen**
Depends on https://github.com/SFTtech/openage/pull/1633

This just flattens the parent hierarchy to make the parent invisible and directly show the coordinate values.

### CODE REVIEW

**Review by TheJJ — APPROVED** [review]
nice!

maybe we can split this into multiple files already

**Comment by heinezen** [comment]
@TheJJ Wouldn't this require switching away from the decorator method? I would like to keep that for now, since it makes adding new printers pretty easy.

**Comment by TheJJ** [comment]
the decorator can be imported like any regular function, no?

**Comment by heinezen** [comment]
@TheJJ Yes, but to use the decorator, the module with the classes would have to be imported too. And somehow, gdb doesn't seem to like that. At least I get errors when I try that for the .gdbinit file but gdb doesn't print the exact issue. I'm not sure how to solve this yet, so having the printers all in one file is the best solution right now.

**Review by TheJJ — APPROVED** [review]
maybe leave a note in the cpp code to remember to update the pretty printer when changing it :)

**Comment by heinezen** [comment]
@TheJJ Done :)

**Review by TheJJ — DISMISSED** [review]

**Comment by heinezen** [comment]
Now it should be good to merge, finally

**Review by TheJJ — APPROVED** [review]

**Pull request merged**
